#!/usr/bin/env bash
set -euo pipefail
BASE="${VEXORA_PUBLIC_URL:-http://${VEXORA_IP:-SERVER-IP}:8080}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                 VEXORA 1.0.0"
echo "              Installation Complete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
printf "🌐 URL      : %s\n" "$BASE"
printf "🛒 Shop     : %s/shop/\n" "$BASE"
printf "🔐 Admin    : %s/admin/\n" "$BASE"
printf "⚙ Config   : /etc/vexora/.env\n"
printf "📜 Cert     : %s\n" "${VEXORA_CERT_PATH:-not-issued}"
printf "🔑 Key      : %s\n" "${VEXORA_KEY_PATH:-not-issued}"
printf "🧩 CLI      : vexora\n"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
